"""add hashed password to users

Revision ID: f582392f6b94
Revises: e37c6036b9eb
Create Date: 2026-09-24 15:35:35.762685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f582392f6b94'
down_revision: Union[str, Sequence[str], None] = 'e37c6036b9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "hashed_password",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE users
        SET hashed_password =
        '$argon2id$v=19$m=65536,t=3,p=4$Cw17/5nSPOHlC7nj/SQMtw$kqnu8zyD7n1BzesOqmMVbQk1Zz/w0tOjqqwAO5QWsHY'
        WHERE hashed_password IS NULL
        """
    )

    op.alter_column(
        "users",
        "hashed_password",
        nullable=False,
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
